export default {
  CREATE_TICKET: "CREATE_TICKET",
  UPDATE_TICKET: "UPDATE_TICKET",
  CLOSE_TICKET: "CLOSE_TICKET",
  ASSIGN_TICKET: "ASSIGN_TICKET",
  LOAD_TICKETS: "LOAD_TICKETS",
  LOAD_USERS: "LOAD_USERS",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DEACTIVATE_USER: "DEACTIVATE_USER",
};
